version: '3'
services:
  todotests:
    Image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
  todofront:
    Image: todofrontend
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    depends_on:
      - todoback
  todoback:
    Image: todobackend
    ports:
      - 3001:3001
